max_name_lenght: 50
min_pass_lenght: 6
max_email_lenght: 255
phone_lenght: 10
max_address_lenght: 255
size_gravatar: 60
quantity_per_page: 5
per_page: 10
limit_home: 3
limit_post_home: 1
time_expired: 2
size_picture: 5
limit_picture: [400, 400]
min_content_length: 255
max_title_length: 255
max_sumary_length: 255
max_service_name: 100
display_text: 160
year_stats: 2019
